apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version| replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ template "hostname" .Values.service.url }}
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: {{ template "fullname" . }}
              port:
                name: http
  tls: # < placing a host in the TLS config will indicate a certificate should be created
    - hosts:
        - {{ template "hostname" .Values.service.url }}
      secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "fullname" .)) }}
