service:
  enabled: true
  url: http://my.host.com/
application:
  track: stable
  tier: web
ingress:
  enabled: true
  tls:
    enabled: true
    secretName: ""
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/client-max-body-size: "40m"
    nginx.ingress.kubernetes.io/proxy-body-size: "600m"
    nginx.org/client-max-body-size: "600m"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.erasysconsulting.com"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
postgresql:
  commonAnnotations: {"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"}
  enabled: false
  persistence:
    enabled: true
mysql:
  commonAnnotations: {"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"}
redis:
  commonAnnotations: {"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"}
  auth:
    enabled: false